name: driev
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_splash_screen: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.5
  flutter_otp_text_field: ^1.1.3+2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  mask_text_input_formatter: ^2.9.0
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.1.0
  image_cropper: ^1.5.1
  path: ^1.9.0
  file_picker: ^8.0.1
  path_provider: ^2.1.3
  otp_autofill: ^3.0.2
  google_maps_flutter: ^2.2.8
  location: ^5.0.3
  geolocator: ^11.0.0
  geocoding: ^2.0.1
  flutter_polyline_points: ^2.0.0
  share_plus: ^9.0.0
  flutter_xlider: ^3.5.0
  syncfusion_flutter_sliders: ^25.1.41
  url_launcher: ^6.2.6
  provider: ^6.1.2
  connectivity_plus: ^6.0.3
  animate_do: ^3.3.4
  syncfusion_flutter_core: ^25.1.42
  pin_code_fields: ^8.0.1
  readsms: ^0.0.2+2
  google_maps_flutter_ios: ^2.6.1
  super_tooltip: ^2.0.7
  screenshot: ^3.0.0
  pdf: ^3.10.8
  open_file: ^3.3.2
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.1.1
  #  qrscan: ^0.3.3
  #  image_gallery_saver: ^2.0.3
  #  qr_scanner_with_effect: ^1.0.5
  #  masi_qr_code_scanner: any
  #  qr_code_scanner: ^1.0.1
  #  mobile_scanner: ^2.1.0
  #  otp_pin_field: ^1.2.2
  #  otp_text_field: ^1.1.3
  #  google_fonts: ^6.2.1
  #  sms_autofill: ^2.3.1
  #  qr_scanner_overlay: ^0.0.2
  #  qr_mobile_vision: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app/
    - assets/img/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
          weight: 100
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
